### PR TITLE
Operating system unit tests

### LINKED ISSUE #34: Infinite loop in round_robin
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [X] Error
- [ ] Proposal to the Repository

**Details:**
round_robin gets stuck in an infinite loop for some inputs, for example: `arrivalTime = { 1, 3 }, burstTime = { 2, 3 }`

### LINKED ISSUE #35: Changing tasks not handled correctly in round_robin
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [X] Error
- [ ] Proposal to the Repository

**Details:**

The process of changing tasks in round_robin does not work well, it starts executing tasks again that have been finished already.

### LINKED ISSUE #36: Time is not increased when no tasks are being executed
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [X] Error
- [ ] Proposal to the Repository

**Details:**

### LINKED ISSUE #37: Task is executed even before it arrives in round_robin
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [X] Error
- [ ] Proposal to the Repository

**Details:**

### PR DESCRIPTION
**Pull request by acsbendi**
**Fixes issue:**

Fixes #34, fixes #35, fixes #36, fixes #37.

**Changes:**

Reorganized, fixed and added tests for round_robin.

### CODE REVIEW

File: code/operating_system/include/round_robin_scheduling.hpp [hunk 1]
```diff
@@ -1,6 +1,9 @@
 #ifndef ROUND_ROBIN_SCHEDULING_HPP
 #define ROUND_ROBIN_SCHEDULING_HPP
 
-int round_robin();
+#include <vector>
+
+void round_robin(std::vector<int> arrivalTime, std::vector<int> burstTime,
+        int timeQuantum, double& averageWaitingTime, double& averageTurnaroundTime);
```
Comment (SachiaTheRaven) [inline code/operating_system/include/round_robin_scheduling.hpp]: OK

File: code/operating_system/src/scheduling/round_robin_scheduling/round_robin_scheduling.cpp [hunk 2]
```diff
@@ -1,58 +1,70 @@
...
+                    }
+                }
+            }
+        }
     }
-    cout << "\nAverage Waiting Time is " << waitTime * 1.0 / n;
-    cout << "\nAvg Turnaround Time is " << turnaroundTime * 1.0 / n << "\n";
-    return 0;
+    averageWaitingTime = waitTime * 1.0 / n;
+    averageTurnaroundTime = turnaroundTime * 1.0 / n;
```
Comment (SachiaTheRaven) [inline code/operating_system/src/scheduling/round_robin_scheduling/round_robin_scheduling.cpp]: OK, the needed feature is added correctly.

File: code/operating_system/test/test_round_robin_scheduling.cpp [hunk 3]
```diff
@@ -1,7 +1,139 @@
...
+
+            THEN("The average waiting time is 11.2") {
+                REQUIRE(averageWaitingTime == Approx(11.2));
+            }
+
+            THEN("The average turnaround time is 16.4") {
+                REQUIRE(averageTurnaroundTime == Approx(16.4));
+            }
+        }
+    }
```
Comment (SachiaTheRaven) [inline code/operating_system/test/test_round_robin_scheduling.cpp]: OK, test cases are comprehensive.
